<?php
/**
 * Created by PhpStorm.
 * User: richard
 * Date: 7/18/16
 * Time: 4:17 AM
 */

require 'vendor/autoload.php';

//echo 'All good';
$client = Elasticsearch\ClientBuilder::create()->build();


$params = [
    'index' => 'my_index',
    'type' => 'my_type',
    'id' => 'my_id',
    //'body' => ['testField' => 'a_body'],
];

$user_credentials = [
    'id' => 1, // autogenerated, self-incremental
    'type' => 'users',
    'index' => 'users',
    'body' => [
        'password' => 'secret',
        'email' => 'richard@domain.com'
    ],
];

$admin_credentials = [
    'id' => 2, // autogenerated, self-incremental
    'type' => 'users',
    'index' => 'users',
    'body' => [
        'password' => 'admin',
        'email' => 'admin@domain.com'
    ],
];

$credentials = [
    'id' => 2, // autogenerated, self-incremental
    'type' => 'users',
    'index' => 'users',
];

//index a document
//$response = $client -> index($user_credentials);
//$response = $client -> index($admin_credentials);

// get a document

//$response = $client -> get($credentials);
//print_r($response);

// search for a document
$query = [
    'index' => 'users',
    'type' => 'users',
    'body' => [
        'query' => [
            'match' => [ 'email' => 'admin@domain.com']
        ]
    ]
];

$response = $client -> search($query);
//print_r($response);
print_r(json_encode($response, JSON_PRETTY_PRINT));


